server:
  port: 8888
  servlet:
    context-path: /dev-api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "123456"
    type: com.alibaba.druid.pool.DruidDataSource
  banner:
    location: classpath:banner.txt
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.jaux.hotel.**

logging:
  level:
    com.jaux.hotel: debug
    org.springframework: warn
  config:
    classpath:logback-spring.xml